### PR TITLE
Adding undulation fields to GPGGA sentences

### PR DESCRIPTION
**Pull request by bnhhughes**
- Also updates altitude field to be double

### CODE REVIEW

**Comment by bnhhughes** [comment]
I may end up needing to push another small change for default values to determine whether or not undulation was set, should know shortly.

**Comment by bnhhughes** [comment]
I've had the INVALID_UNDULATION changes for a while but forgot to push them up.  This should be good to go now.

**Comment by bnhhughes** [comment]
@jhaws1982 Do you want to just commit the changes to the CMakeLists.txt file and remove the patch or leave it how it is and always patch it?  I just thought it was a bit odd to have a patch file that only patches the CMakeLists.txt file and then there are a bunch of other changes in the rest of the source that are different from the origin repo, but aren't in a patch file and just live in your fork.

**Comment by jhaws1982** [comment]
Just to get this written down, let's see about rebasing to upstream and then merging all these changes back in. As far as the CMakeLists.txt patch goes, I'd say we can have it in here as long as it doesn't break a "normal" build (i.e. if we push upstream it won't break their typical build pattern).

**Comment by bnhhughes** [comment]
I think adding the `-fPIC` flag is probably safe, but I'm guessing they won't want the install path change (from `/usr/lib/nmea/` to `lib/nmea`) so maybe it's better to just leave it as a patch.

**Comment by bnhhughes** [comment]
Closing this in favor of https://github.com/jhaws1982/libnmea/pull/4 which includes these changes as well as the latest from the original libnmea repo

**Pull request closed without merging**
